const contentInput = document.getElementById('contentInput');
const charCount = document.getElementById('charCount');
const clearButton = document.getElementById('clearButton');
const pasteButton = document.getElementById('pasteButton');
const findSolutionButton = document.getElementById('findSolutionButton');
const newQueryButton = document.getElementById('newQueryButton');
const pasteButtonText = document.getElementById('pasteButtonText');
const pasteButtonIcon = document.getElementById('pasteButtonIcon');
const inputCard = document.getElementById('inputCard');
const answerCard = document.getElementById('answerCard');
const loadingSpinner = document.getElementById('loadingSpinner');
const answerText = document.getElementById('answerText');

contentInput.addEventListener('input', () => {
    const count = contentInput.value.length;
    charCount.textContent = `${count} character${count !== 1 ? 's' : ''}`;
});

clearButton.addEventListener('click', () => {
    contentInput.value = '';
    contentInput.dispatchEvent(new Event('input'));
});

pasteButton.addEventListener('click', () => {
    contentInput.focus();
    try {
        const successful = document.execCommand('paste');
        if (!successful) {
            console.error('Paste command was not successful. The browser may have blocked it.');
        }
        setTimeout(() => contentInput.dispatchEvent(new Event('input')), 100);
    } catch (err) {
        console.error('Failed to execute paste command: ', err);
    }
});

findSolutionButton.addEventListener('click', () => {
    if (contentInput.value.trim() === '') {
        contentInput.classList.add('border-red-500', 'animate-pulse');
        setTimeout(() => {
            contentInput.classList.remove('border-red-500', 'animate-pulse');
        }, 1500);
        return;
    }
    
    inputCard.classList.add('hidden');
    loadingSpinner.classList.remove('hidden');

    setTimeout(() => {
        loadingSpinner.classList.add('hidden');
        
        answerText.innerHTML = `
            <p class="mb-4">Based on the content provided, here is the generated solution:</p>
            <p class="mb-2"><strong class="text-emerald-400">Key Point 1:</strong> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor.</p>
            <p class="mb-2"><strong class="text-emerald-400">Key Point 2:</strong> Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. Proin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat.</p>
            <p class="mb-4"><strong class="text-emerald-400">Conclusion:</strong> Duis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. Ut in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales.</p>
            <p>This solution was generated by a state-of-the-art language model.</p>
        `;

        answerCard.classList.remove('hidden');

    }, 2000);
});

newQueryButton.addEventListener('click', () => {
    answerCard.classList.add('hidden');
    inputCard.classList.remove('hidden');
    contentInput.value = '';
    contentInput.dispatchEvent(new Event('input'));
});

const dropzone = document.querySelector('main');

dropzone.addEventListener('dragenter', (e) => {
    e.preventDefault();
    e.stopPropagation();
    if(!inputCard.classList.contains('hidden')) {
         inputCard.classList.add('scale-105', 'shadow-blue-500/30');
         inputCard.classList.remove('shadow-blue-500/10');
    }
});

dropzone.addEventListener('dragleave', (e) => {
    e.preventDefault();
    e.stopPropagation();
     if(!inputCard.classList.contains('hidden')) {
        inputCard.classList.remove('scale-105', 'shadow-blue-500/30');
        inputCard.classList.add('shadow-blue-500/10');
     }
});

dropzone.addEventListener('dragover', (e) => {
    e.preventDefault();
    e.stopPropagation();
});

dropzone.addEventListener('drop', (e) => {
    e.preventDefault();
    e.stopPropagation();
     if(!inputCard.classList.contains('hidden')) {
        inputCard.classList.remove('scale-105', 'shadow-blue-500/30');
        inputCard.classList.add('shadow-blue-500/10');
     }
});
